name: Bug Report
description: Create a report to help us improve.
title: "[BUG] Title"
assignees: ''
labels: bug
body:
  - type: markdown
    attributes:
      value: |
        ## Welcome!
        Thanks for taking the time to fill out this bug! If you need real-time help, join us on Discord.
        
  - type: input
    id: bug_description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: "e.g., The app crashes when I click the submit button."
    validations:
      required: true
      
  - type: textarea
    id: reproduction_steps
    attributes:
      label: To Reproduce
      description: How do you trigger this bug? Please walk us through it step by step.
      value: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
      
  - type: input
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: "e.g., The app should save the input."
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS
      description: What operating system are you using?
      placeholder: "e.g., Windows, Mac, Linux"
      
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the application are you using?
      placeholder: "e.g., 1.0.0"
      
  - type: input
    id: browser
    attributes:
      label: Browser
      description: What browser are you using?
      placeholder: "e.g., Chrome, Firefox, Safari"
      
  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: "e.g., This bug occurs when..."
      
