# Generated by Django 4.2.4 on 2023-08-30 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("drive", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Share",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_with",
                        to="drive.file",
                    ),
                ),
                (
                    "user",
                    models.ManyToManyField(
                        related_name="shared_files", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
