# Generated by Django 4.2.4 on 2023-08-31 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("drive", "0003_notification_share_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="share",
            name="notification",
        ),
        migrations.RemoveField(
            model_name="share",
            name="user",
        ),
        migrations.AddField(
            model_name="share",
            name="receiver",
            field=models.ManyToManyField(
                related_name="shared_with", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="share",
            name="sender",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_files",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="share",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared",
                to="drive.file",
            ),
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
